[package]
    authors     = ["Hèctor Morales <hector.morales.carnice@gmail.com>"]
    description = "A story line manager"
    edition     = "2021"
    license     = "MIT"
    name        = "plotline"
    readme      = "../README.md"
    repository  = "https://github.com/alvidir/plotline"
    version     = "0.1.0"

    # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
    clap = {version = "4.4.6", optional = true, features = [
        "derive",
        "env",
        "string",
    ]}
    dirs = {version = "5.0.1", optional = true}
    once_cell = "1.18.0"
    regex = "1.8.4"
    serde = {version = "1.0.164", features = ["derive", "rc"]} # data parser
    serde_yaml = "0.9.25"
    strum = "0.25.0"
    strum_macros = "0.25.3"
    thiserror = "1.0.49"
    uuid = {version = "1.4.1", features = ["v4"]}

[features]
    cli     = ["clap", "dirs"]
    default = ["cli"]

[lib]
    name = "plotline"
    path = "src/lib.rs"

[[bin]]
    name              = "plot"
    path              = "src/bin/cli.rs"
    required-features = ["cli"]
