[package]
    authors     = ["Hèctor Morales <hector.morales.carnice@gmail.com>"]
    description = "A story line manager"
    edition     = "2021"
    license     = "MIT"
    name        = "plotline"
    readme      = "../README.md"
    repository  = "https://github.com/alvidir/plotline"
    version     = "0.1.0"

    # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
    name = "plotline"
    path = "src/lib.rs"
