[workspace]
members = ["alvidir", "alvidir-cli", "alvidir-macros"]
resolver = "2"

[workspace.dependencies]
alvidir-macros.path = "alvidir-macros"
log = "0.4.22"
serde = "1.0.215"
thiserror = "2.0.3"
tracing = "0.1.41"
