[package]
name = "alvidir-macros"
description = "Proc macros complementary to the alvidir crate."
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"

[lib]
path = "src/lib.rs"
proc-macro = true
